
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Product } from '../../types/products';
import { BrandProfile } from '../../types/brand';

export const generateLineSheetPDF = async (products: Product[], brand?: BrandProfile | null) => {
  const doc: any = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 15;
  
  // --- Brand Header ---
  doc.setFont("times", "bold");
  doc.setFontSize(24);
  const brandName = brand?.brandName || "FashionOS Studio";
  doc.text(brandName.toUpperCase(), margin, 25);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("SS25 WHOLESALE COLLECTION", margin, 32);
  
  // Contact Info (Right aligned)
  const contactX = pageWidth - margin;
  doc.text(`Web: ${brand?.websiteUrl || 'www.fashionos.co'}`, contactX, 25, { align: 'right' });
  doc.text(`IG: ${brand?.instagramHandle || '@fashionos'}`, contactX, 30, { align: 'right' });
  doc.text(`Email: wholesale@${brand?.brandName?.toLowerCase().replace(' ', '') || 'fashionos'}.com`, contactX, 35, { align: 'right' });

  doc.setDrawColor(200);
  doc.line(margin, 40, pageWidth - margin, 40);

  // --- Product Grid Logic ---
  let yPos = 50;
  const colWidth = (pageWidth - (margin * 2) - 10) / 2; // 2 Columns
  const rowHeight = 90; 
  let col = 0;

  // Pre-load images if possible (simplified for client-side demo)
  // In prod, this would use the `fileHelpers` to fetch/base64 avatars.
  
  for (let i = 0; i < products.length; i++) {
    const p = products[i];
    
    // Check for page break
    if (yPos + rowHeight > pageHeight - 20) {
      doc.addPage();
      yPos = 20; // Reset Y
      col = 0;
    }

    const xPos = margin + (col * (colWidth + 10));

    // Image Placeholder or Actual Image
    // Using a grey placeholder rect if loading fails, or just the rect for style
    doc.setFillColor(245, 245, 245);
    doc.rect(xPos, yPos, 40, 50, 'F'); // Image background
    
    // Try to add image if it's a data URI or simple URL (Cross-origin might fail without proxy)
    if (p.img) {
       try {
          // Attempt to load image - simplified for this context
          // In a real app, you'd await fetch(p.img).then(r => r.blob()) etc.
          // For now, we assume the URL is accessible or we skip
          // doc.addImage(p.img, 'JPEG', xPos, yPos, 40, 50, undefined, 'FAST'); 
       } catch (e) {}
    }

    // Text Details (Next to image)
    const textX = xPos + 45;
    const textWidth = colWidth - 45;

    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(p.name, textX, yPos + 5);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80);
    doc.text(`SKU: ${p.sku}`, textX, yPos + 12);
    doc.text(`Category: ${p.category || 'Apparel'}`, textX, yPos + 17);

    // Pricing Box
    doc.setFillColor(250, 250, 250);
    doc.rect(textX, yPos + 22, textWidth, 18, 'F');
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text(`WSP: $${p.wholesalePrice || '0.00'}`, textX + 2, yPos + 29);
    
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`RRP: ${p.price}`, textX + 2, yPos + 36);

    // Logistics
    doc.setFontSize(8);
    doc.text(`MOQ: ${p.moq || 1} units`, textX, yPos + 48);
    doc.text(`Case Pack: ${p.casePack || 1}`, textX + 30, yPos + 48);

    // Description (Truncated)
    if (p.description) {
        const desc = p.description.length > 80 ? p.description.substring(0, 80) + '...' : p.description;
        const splitDesc = doc.splitTextToSize(desc, colWidth);
        doc.text(splitDesc, xPos, yPos + 58);
    }

    // Move column/row
    if (col === 1) {
      col = 0;
      yPos += rowHeight;
    } else {
      col = 1;
    }
  }

  // --- Terms Footer ---
  const pageCount = doc.internal.getNumberOfPages();
  for(let j = 1; j <= pageCount; j++) {
    doc.setPage(j);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${j} of ${pageCount} | Generated by FashionOS`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(`${brandName.replace(/ /g, '_')}_LineSheet.pdf`);
};
