
import React from 'react';
import { BarChart2, Heart, Smartphone, Video, ShoppingBag } from 'lucide-react';

export const InstagramValue: React.FC = () => {
  const stats = [
     { value: "3x", label: "Higher Reach", desc: "Reels vs Static Posts", icon: Video },
     { value: "58%", label: "Purchase Intent", desc: "Boost from Quality Visuals", icon: Heart },
     { value: "70%", label: "Discovery", desc: "Shoppers find new products", icon: Smartphone },
     { value: "+49%", label: "Interactions", desc: "Generated by Video", icon: BarChart2 },
     { value: "30%", label: "Conversion Lift", desc: "Using Instagram Shops", icon: ShoppingBag }
  ];

  return (
    <section className="py-24 px-6 bg-white reveal-on-scroll">
      <div className="max-w-[1440px] mx-auto grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
        
        {/* Left: Stats with Visual Hierarchy */}
        <div className="space-y-12">
           <div>
             <span className="text-xs font-bold tracking-[0.2em] uppercase text-gray-400 block mb-4">The Power of Visuals</span>
             <h2 className="font-serif text-4xl md:text-5xl text-primary leading-tight">
                Why invest in <br/>premium content?
             </h2>
           </div>
           
           <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-10">
              {stats.map((stat, i) => (
                 <div key={i} className="flex flex-col group">
                    <div className="flex items-center gap-3 mb-2">
                       <stat.icon size={20} className="text-gray-300 group-hover:text-purple-600 transition-colors duration-500" />
                       <span className="text-xs font-bold uppercase tracking-widest text-gray-400">{stat.label}</span>
                    </div>
                    <div className="text-5xl font-serif text-black mb-1">{stat.value}</div>
                    <p className="text-sm text-gray-500 font-light">{stat.desc}</p>
                 </div>
              ))}
           </div>
        </div>

        {/* Right: Interactive Comparison Card */}
        <div className="relative bg-[#F7F5F3] p-10 rounded-2xl overflow-hidden group hover:shadow-2xl transition-all duration-700 border border-gray-100 mt-8 lg:mt-0">
           {/* Abstract Glow */}
           <div className="absolute top-0 right-0 w-80 h-80 bg-purple-200 rounded-full blur-[100px] opacity-0 group-hover:opacity-40 -mr-20 -mt-20 transition-opacity duration-700"></div>
           
           <h3 className="font-serif text-3xl mb-6 relative z-10 text-primary">Better Content = <br/>Better Results.</h3>
           <p className="text-gray-500 mb-10 relative z-10 leading-relaxed max-w-md">
              In a crowded feed, mediocrity is invisible. We create scroll-stopping assets that elevate your brand perception and drive tangible business results.
           </p>

           <div className="grid grid-cols-2 gap-6 relative z-10">
              <div className="space-y-3 opacity-60 group-hover:opacity-40 transition-opacity">
                 <div className="aspect-[4/5] bg-gray-300 rounded-lg overflow-hidden grayscale">
                    <img src="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=2820&auto=format&fit=crop" className="w-full h-full object-cover blur-[1px]" alt="Standard" />
                 </div>
                 <p className="text-[10px] uppercase tracking-widest text-gray-500 font-bold text-center">Standard</p>
              </div>
              
              <div className="space-y-3 relative -mt-6">
                 <div className="aspect-[4/5] bg-white rounded-lg overflow-hidden shadow-xl ring-1 ring-black/5 transform transition-transform duration-500 group-hover:scale-105 group-hover:-translate-y-2">
                    <img src="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=2820&auto=format&fit=crop" className="w-full h-full object-cover" alt="FashionOS Premium" />
                 </div>
                 <p className="text-[10px] uppercase tracking-widest text-black font-bold text-center">FashionOS</p>
                 
                 {/* Floating Badge */}
                 <div className="absolute top-2 right-2 bg-green-500 text-white text-[10px] font-bold px-2 py-1 rounded-full shadow-lg transform scale-0 group-hover:scale-100 transition-transform duration-500 delay-100">
                    +140% Reach
                 </div>
              </div>
           </div>
        </div>

      </div>
    </section>
  );
};
